{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ats-interview-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "ats-interview-service.fullname" . }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ include "ats-interview-service.fullname" . }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.metrics.scrapeInterval | default "30s" }}
{{- end }}
