replicaCount: 1

# image:
#   repository: glacius27/ats-candidate-service
#   tag: "latest"
#   pullPolicy: IfNotPresent

image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

service:
  port: 8080

env:
  ASPNETCORE_ENVIRONMENT: "Development"
  EnableSwagger: "true"

  # PostgreSQL
  POSTGRES_HOST: "candidates-postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "ats_candidates"
  POSTGRES_USER: "ats"

  # Minio
  MinioSettings__Endpoint: "minio:9000"
  MinioSettings__BucketName: "resumes"
  MinioSettings__WithSSL: "false"

  # RabbitMQ
  RabbitMq__HostName: "rabbitmq"
  RabbitMq__Port: "5672"
  RabbitMq__UserName: "ats_user"
  RabbitMq__Exchange: "ats.exchange"
  RabbitMq__ClientId: "candidate"

  # Service Discovery - Disabled, using Kubernetes DNS
  SERVICE_DISCOVERY_ENABLED: "false"
  
  # Kubernetes service URLs (using DNS)
  AuthService__BaseUrl: "http://ats-authorization-service:8080"

secretEnv:
  POSTGRES_PASSWORD: "ats_pass"
  RabbitMq__Password: "ats_pass"
  MinioSettings__AccessKey: "minioadmin"
  MinioSettings__SecretKey: "minioadmin"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: candidate.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

metrics:
  enabled: true
  scrapeInterval: "30s"