replicaCount: 1

# image:
#   repository: glacius27/ats-candidate-service
#   tag: "latest"
#   pullPolicy: IfNotPresent

image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

service:
  port: 8080

env:
  ASPNETCORE_ENVIRONMENT: "Development"
  EnableSwagger: "true"

  # PostgreSQL
  POSTGRES_HOST: "candidates-postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "ats_candidates"
  POSTGRES_USER: "ats"

  # Minio
  MinioSettings__Endpoint: "minio:9000"
  MinioSettings__AccessKey: "minioadmin"
  MinioSettings__SecretKey: "minioadmin"
  MinioSettings__BucketName: "resumes"
  MinioSettings__WithSSL: "false"

  # RabbitMQ
  RabbitMq__HostName: "rabbitmq"
  RabbitMq__Port: "5672"
  RabbitMq__UserName: "ats_user"
  RabbitMq__Exchange: "ats.exchange"
  RabbitMq__ClientId: "candidate"

  SERVICE_DISCOVERY_ENABLED: "false"

secretEnv:
  POSTGRES_PASSWORD: "ats_pass"
  RabbitMq__Password: "ats_pass"