apiVersion: v2
name: ats-observability
description: Observability stack for ATS (Grafana, Prometheus, Loki)
type: application
version: 0.1.0

dependencies:
  - name: kube-prometheus-stack
    version: "62.3.0"
    repository: "https://prometheus-community.github.io/helm-charts"
