apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ats-recruitment-service.fullname" . }}-secret
type: Opaque
stringData:
{{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: "{{ $value }}"
{{- end }}
