{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: "{{ .Values.keycloak.db.password }}"
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-db
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  selector:
    app: keycloak-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-db
  template:
    metadata:
      labels:
        app: keycloak-db
    spec:
      containers:
        - name: postgres
          image: {{ .Values.keycloak.db.image }}
          env:
            - name: POSTGRES_DB
              value: "{{ .Values.keycloak.db.dbName }}"
            - name: POSTGRES_USER
              value: "{{ .Values.keycloak.db.username }}"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-secret
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: keycloak-db-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: keycloak-db-data
          emptyDir: {}
{{- end }}