{{- if .Values.postgres.enabled }}

apiVersion: v1
kind: Secret
metadata:
  name: ats-postgres-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: "{{ .Values.postgres.password }}"
---
{{- range .Values.postgres.instances }}

apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-postgres" .name }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: {{ printf "%s-postgres" .name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-postgres" .name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ printf "%s-postgres" .name }}
  template:
    metadata:
      labels:
        app: {{ printf "%s-postgres" .name }}
    spec:
      containers:
        - name: postgres
          image: {{ $.Values.postgres.image }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "{{ .dbName }}"
            - name: POSTGRES_USER
              value: "{{ $.Values.postgres.username }}"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ats-postgres-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          emptyDir: {}
---
{{- end }}
{{- end }}